name: "commodity_dbt"
version: "1.0.0"
profile: "commodity_dbt"

model-paths: ["models"]

packages-install-path: "/tmp/dbt_packages"

models:
  commodity_dbt:
    staging:
      materialized: view
    marts:
      materialized: table