apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    uid: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false