{
 "title": "Market Analysis",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH current_utc AS (\r\n  SELECT now() AT TIME ZONE 'UTC' AS utc_ts\r\n)\r\nSELECT\r\n  'XAU/USD' || ' ' ||\r\n  CASE\r\n    WHEN (\r\n      (extract(dow FROM utc_ts) = 5 AND utc_ts::time >= TIME '22:00')\r\n      OR extract(dow FROM utc_ts) = 6\r\n      OR (extract(dow FROM utc_ts) = 0 AND utc_ts::time < TIME '22:00')\r\n    )\r\n    THEN '● CLOSED'\r\n    ELSE '● OPEN'\r\n  END AS gold_status,\r\n\r\n  'BTC/USD' || ' ' || '● OPEN' AS btc_status,\r\n\r\n  'EUR/USD' || ' ' ||\r\n  CASE\r\n    WHEN (\r\n      (extract(dow FROM utc_ts) = 5 AND utc_ts::time >= TIME '22:00')\r\n      OR extract(dow FROM utc_ts) = 6\r\n      OR (extract(dow FROM utc_ts) = 0 AND utc_ts::time < TIME '22:00')\r\n    )\r\n    THEN '● CLOSED'\r\n    ELSE '● OPEN'\r\n  END AS eurusd_status\r\n\r\nFROM current_utc;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 20, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  'As of ' ||\r\n  to_char(event_ts, 'HH24:MI') ||\r\n  ' UTC ' ||\r\n  to_char(event_ts, 'DD/MM/YYYY') AS last_update\r\nFROM public.raw_prices\r\nWHERE commodity = 'bitcoin'\r\nORDER BY event_ts DESC, event_id DESC\r\nLIMIT 1;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 20, "x": 2, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 2, "y": 2 },
   "options": {
    "content": "<div style=\"\n  text-align: center;\n  margin-bottom: 6px;\n  font-size: 22px;\n  font-weight: 600;\n  color: rgb(195, 205, 220);\n  letter-spacing: 1px;\n\">\n  MARKET ANALYSIS (1h)\n</div>\n\n<div style=\"\n  height: 1px;\n  background-color: rgba(255,255,255,0.12);\n  width: 25%;\n  margin: 0 auto 20px auto;\n\"></div>"
   }
  },
  {
   "title": "Market Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 2, "y": 5 },
   "targets": [
    {
     "rawSql": "with latest_hour as (\r\n    select max(hour_bucket) as hour_bucket\r\n    from analytics.mart_price_volatility_1h\r\n),\r\n\r\nvolatility as (\r\n    select\r\n        symbol,\r\n        avg_price,\r\n        price_range,\r\n        range_pct\r\n    from analytics.mart_price_volatility_1h\r\n    where hour_bucket = (select hour_bucket from latest_hour)\r\n),\r\n\r\nmoves as (\r\n    select\r\n        symbol,\r\n        max(abs(price_change_pct)) as largest_move,\r\n        count(*) as events\r\n    from analytics.mart_price_events\r\n    where event_ts >= now() - interval '1 hour'\r\n    group by symbol\r\n)\r\n\r\nselect\r\n    v.symbol as \"Instrument\",\r\n    round(v.avg_price::numeric, 2) as \"Avg Price\",\r\n    round(v.price_range::numeric, 2) as \"Price Range\",\r\n    round(v.range_pct::numeric, 3) as \"Hourly Range\",\r\n    round(coalesce(m.largest_move,0)::numeric, 3) as \"Largest Move\",\r\n    coalesce(m.events,0) as \"Events\"\r\nfrom volatility v\r\nleft join moves m\r\n    on v.symbol = m.symbol\r\norder by v.range_pct desc;"
    }
   ]
  },
  {
   "title": "Price Statistics",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 5 },
   "targets": [
    {
     "rawSql": "select\r\n    symbol as \"Instrument\",\r\n    avg_price as \"Avg Price\",\r\n    price_range as \"Range\",\r\n    range_pct as \"Range %\",\r\n    price_stddev as \"StdDev\",\r\n    observations_count as \"Observations\"\r\nfrom analytics.mart_price_volatility_1h\r\nwhere hour_bucket = (\r\n    select max(hour_bucket)\r\n    from analytics.mart_price_volatility_1h\r\n)\r\norder by range_pct desc;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 20, "x": 2, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 2, "y": 11 },
   "options": {
    "content": "<div style=\"\n  text-align: center;\n  margin-bottom: 6px;\n  font-size: 22px;\n  font-weight: 600;\n  color: rgb(195, 205, 220);\n  letter-spacing: 1px;\n\">\n  VOLATILITY & EVENTS\n</div>\n\n<div style=\"\n  height: 1px;\n  background-color: rgba(255,255,255,0.12);\n  width: 25%;\n  margin: 0 auto 20px auto;\n\"></div>"
   }
  },
  {
   "title": "Hourly Range",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 9, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\r\n    hour_bucket as \"time\",\r\n    symbol,\r\n    round(range_pct::numeric,2) as \"Range\"\r\nfrom analytics.mart_price_volatility_1h\r\norder by 1,2;"
    }
   ]
  },
  {
   "title": "Recent Price Events",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 13, "y": 14 },
   "targets": [
    {
     "rawSql": "select\r\n    event_ts as \"Time\",\r\n    symbol as \"Instrument\",\r\n    event_type as \"Event\",\r\n    round(price_change_pct, 2) as \"Change\",\r\n    case\r\n        when symbol = 'EUR/USD' then to_char(prev_price::numeric, 'FM9999999990.0000')\r\n        else to_char(prev_price::numeric, 'FM9999999990.00')\r\n    end as \"Prev Price\",\r\n    case\r\n        when symbol = 'EUR/USD' then to_char(current_price::numeric, 'FM9999999990.0000')\r\n        else to_char(current_price::numeric, 'FM9999999990.00')\r\n    end as \"Current Price\"\r\nfrom analytics.mart_price_events\r\norder by event_ts desc\r\nlimit 100;"
    }
   ]
  }
 ]
}