{
 "title": "Market Analysis",
 "time": { "from": "now-6d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  'As of ' ||\r\n  to_char(event_ts, 'HH24:MI') ||\r\n  ' UTC ' ||\r\n  to_char(event_ts, 'DD/MM/YYYY') AS last_update\r\nFROM public.raw_prices\r\nWHERE commodity = 'bitcoin'\r\nORDER BY event_ts DESC, event_id DESC\r\nLIMIT 1;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 16, "x": 4, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH current_utc AS (\r\n  SELECT now() AT TIME ZONE 'UTC' AS utc_ts\r\n)\r\n\r\nSELECT\r\n  'XAU/USD' as instrument,\r\n  CASE\r\n    WHEN (\r\n      (extract(dow FROM utc_ts) = 5 AND utc_ts::time >= TIME '22:00')\r\n      OR extract(dow FROM utc_ts) = 6\r\n      OR (extract(dow FROM utc_ts) = 0 AND utc_ts::time < TIME '22:00')\r\n    )\r\n    THEN '● CLOSED'\r\n    ELSE '● OPEN'\r\n  END AS status\r\n\r\nFROM current_utc\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n  'BTC/USD',\r\n  '● OPEN'\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n  'EUR/USD',\r\n  CASE\r\n    WHEN (\r\n      (extract(dow FROM utc_ts) = 5 AND utc_ts::time >= TIME '22:00')\r\n      OR extract(dow FROM utc_ts) = 6\r\n      OR (extract(dow FROM utc_ts) = 0 AND utc_ts::time < TIME '22:00')\r\n    )\r\n    THEN '● CLOSED'\r\n    ELSE '● OPEN'\r\n  END\r\nFROM current_utc;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 4, "y": 1 },
   "options": {
    "content": "<div style=\"\n  text-align: center;\n  margin-bottom: 6px;\n  font-size: 22px;\n  font-weight: 600;\n  color: rgb(195, 205, 220);\n  letter-spacing: 1px;\n\">\n  MARKET ANALYSIS (1h)\n</div>\n\n<div style=\"\n  height: 1px;\n  background-color: rgba(255,255,255,0.12);\n  width: 25%;\n  margin: 0 auto 20px auto;\n\"></div>"
   }
  },
  {
   "title": "Price Statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 3 },
   "targets": [
    {
     "rawSql": "with latest_hour as (\r\n    select max(hour_bucket) as hour_bucket\r\n    from analytics.mart_price_volatility_1h\r\n),\r\nvolatility as (\r\n    select symbol, avg_price, price_range, range_pct, price_stddev, observations_count\r\n    from analytics.mart_price_volatility_1h\r\n    where hour_bucket = (select hour_bucket from latest_hour)\r\n),\r\nmoves as (\r\n    select symbol, max(abs(price_change_pct)) as largest_move, count(*) as events\r\n    from analytics.mart_price_events\r\n    where event_ts >= (select hour_bucket from latest_hour)\r\n      and event_ts <  (select hour_bucket + interval '1 hour' from latest_hour)\r\n    group by symbol\r\n)\r\nselect\r\n    v.symbol as \"Instrument\",\r\n    case when v.symbol = 'EUR/USD' then to_char(v.avg_price::numeric, 'FM9999999990.0000')\r\n         else to_char(v.avg_price::numeric, 'FM9999999990.00') end as \"Avg Price\",\r\n    round(v.price_range::numeric, 4) as \"Price Range\",\r\n    round(v.range_pct::numeric, 3) as \"Range %\",\r\n    round(v.price_stddev::numeric, 4) as \"StdDev\",\r\n    round(coalesce(m.largest_move,0)::numeric, 3) as \"Largest Move\",\r\n    coalesce(m.events,0) as \"Events\",\r\n    v.observations_count as \"Observations\"\r\nfrom volatility v\r\nleft join moves m on v.symbol = m.symbol\r\norder by v.range_pct desc;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 14, "x": 5, "y": 9 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 5, "y": 11 },
   "options": {
    "content": "<div style=\"\n  text-align: center;\n  margin-bottom: 6px;\n  font-size: 22px;\n  font-weight: 600;\n  color: rgb(195, 205, 220);\n  letter-spacing: 1px;\n\">\n  VOLATILITY & EVENTS\n</div>\n\n<div style=\"\n  height: 1px;\n  background-color: rgba(255,255,255,0.12);\n  width: 25%;\n  margin: 0 auto 20px auto;\n\"></div>"
   }
  },
  {
   "title": "Hourly Price Change (%)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    hour_bucket AS \"time\",\r\n    round(range_pct::numeric, 2) AS \"Range\",\r\n    symbol AS \"metric\"\r\nFROM analytics.mart_price_volatility_1h\r\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Recent Price Events",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 13, "y": 13 },
   "targets": [
    {
     "rawSql": "select\r\n    to_char(event_ts AT TIME ZONE 'UTC', 'YYYY-Mon-DD') as \"Date\",\r\n    to_char(event_ts AT TIME ZONE 'UTC', 'HH24:MI:SS') as \"Time\",\r\n    symbol as \"Instrument\",\r\n    event_type as \"Event\",\r\n    round(price_change_pct, 2) as \"Change\",\r\n    case\r\n        when symbol = 'EUR/USD' then to_char(prev_price::numeric, 'FM9999999990.0000')\r\n        else to_char(prev_price::numeric, 'FM9999999990.00')\r\n    end as \"Prev Price\",\r\n    case\r\n        when symbol = 'EUR/USD' then to_char(current_price::numeric, 'FM9999999990.0000')\r\n        else to_char(current_price::numeric, 'FM9999999990.00')\r\n    end as \"Current Price\"\r\nfrom analytics.mart_price_events\r\norder by event_ts desc\r\nlimit 100;"
    }
   ]
  }
 ]
}